name: CMake multiple compilers

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake 
        -S ${{github.workspace}}
        -B ${{github.workspace}}/build
        -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build