name: Build and test

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{github.workspace}}/vcpkg'

    - name: Configure CMake
      run: cmake 
        -S ${{github.workspace}}
        -B ${{github.workspace}}/build
        -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
        -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure